import exitHook from 'async-exit-hook'
import type { Server } from 'http'
import { build, type InlineConfig } from 'vite'
import { userScriptPlugin } from '../../vite-plugin-userscript'
import { resolve } from 'path'
import { sendMessage } from './web-socket-server'
import { devServerConfig } from './config'

export interface RegistryWatcher {
  url: string
  instance: any
}

export const watchers: RegistryWatcher[] = []

export const parseRegistryUrl = (url: string) => {
  /* example: http://localhost:2333/registry/dist/components/feeds/copy-link.js
  -> src: ./registry/lib/components/
  -> type: component
  -> entry: ./registry/lib/components/feeds/copy-link/index.ts
  */
  const regex = new RegExp('/registry/dist/([^/]+)s/(.+)\\.js')
  const match = url.match(regex)
  if (!match) {
    return null
  }
  const [, type, id] = match
  const src = `./registry/lib/${type}s/`
  return {
    src,
    type,
    entry: resolve(src, id, 'index.ts'),
  }
}

export const stopInstance = (watcher: any, onClose: () => void) => {
  watcher.close().then(() => {
    onClose()
  })
}

export const startRegistryWatcher = async (url: string, originalEntry: string) => {
  console.log(`功能编译中... ${url}`)
  
  const registryInfo = parseRegistryUrl(url)
  if (!registryInfo) {
    console.error(`无法解析注册表URL: ${url}`)
    return
  }
  
  // 创建Vite配置用于构建特定组件
  const viteConfig: InlineConfig = {
    plugins: [
      userScriptPlugin({
        meta: {
          name: `Bilibili Evolved ${registryInfo.type} - ${registryInfo.src}`,
          description: '动态构建的组件',
          version: '[version]',
          author: 'Generated by dev-server-vite',
          license: 'MIT'
        }
      })
    ],
    build: {
      watch: {}, // 启用监听模式
      lib: {
        entry: registryInfo.entry,
        name: `BilibiliEvolved${registryInfo.type}`,
        formats: ['iife'],
      },
      outDir: `./registry/dist/${registryInfo.type}s/${registryInfo.id}`,
      rollupOptions: {
        output: {
          // 输出单个JS文件
          entryFileNames: '[name].js',
        },
      },
    },
    define: {
      __VUE_OPTIONS_API__: true,
      __VUE_PROD_DEVTOOLS__: false,
    },
  }
  
  // 使用Vite构建系统进行监听构建
  const builder = await build(viteConfig)
  
  // 监听构建完成事件
  if (builder && typeof builder === 'object' && 'close' in builder) {
    // 如果是watch模式，可以监听close事件
    const watcher = builder
    watcher.on('event', (event) => {
      if (event.code === 'BUNDLE_END') {
        console.log('功能已编译:', url)
        sendMessage({
          type: 'itemUpdate',
          path: url,
          sessions: watchers.map(it => it.url),
        })
      }
    })
  }
  
  exitHook(exit => {
    if (builder && typeof builder === 'object' && 'close' in builder) {
      builder.close().then(() => {
        console.log(`功能编译器已退出: ${url}`)
        exit()
      })
    } else {
      console.log(`功能编译器已退出: ${url}`)
      exit()
    }
  })
  
  // 检查最大监听器数量
  const { maxWatchers } = devServerConfig
  if (watchers.length >= maxWatchers!) {
    const oldWatcher = watchers.shift()
    if (oldWatcher) {
      stopInstance(oldWatcher, () => {
        console.log(
          `已达到 maxWatchers 数量 (${maxWatchers}), 退出了功能编译器: ${oldWatcher.url}`,
        )
      })
    }
  }
  
  watchers.push({ url, instance: builder })
}